version: "3"
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_PASSWORD=example
      - MYSQL_USER=flask_docker
      - MYSQL_DATABASE=flask_docker
    # command: mariadb --host 0.0.0.0 -P 3306 --user root -p example
    
  web:
    build: .
    ports:
      - 8000:5000
      - 3306:3306
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  mariadb_data: {}