version: "1"
services:
  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - "db"
    command: ["./wait-for-mysql.sh", "db:5432", "--", "python", "-m", "flask", "run"]
  db:
    image: maria-db
    